// Generated by psc-bundle 0.7.6.1
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Prelude

  //- Functor --------------------------------------------------------------------

  exports.arrayMap = function (f) {
    return function (arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };

  exports.concatArray = function (xs) {
    return function (ys) {
      return xs.concat(ys);
    };
  };

  //- Eq -------------------------------------------------------------------------

  exports.refEq = function (r1) {
    return function (r2) {
      return r1 === r2;
    };
  };                                          

  //- BooleanAlgebra -------------------------------------------------------------

  exports.boolOr = function (b1) {
    return function (b2) {
      return b1 || b2;
    };
  };

  exports.boolAnd = function (b1) {
    return function (b2) {
      return b1 && b2;
    };
  };

  exports.boolNot = function (b) {
    return !b;
  };
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Prelude"];
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Semigroup = function (append) {
      this.append = append;
  };
  var Eq = function (eq) {
      this.eq = eq;
  };
  var Bounded = function (bottom, top) {
      this.bottom = bottom;
      this.top = top;
  };
  var BooleanAlgebra = function (__superclass_Prelude$dotBounded_0, conj, disj, not) {
      this["__superclass_Prelude.Bounded_0"] = __superclass_Prelude$dotBounded_0;
      this.conj = conj;
      this.disj = disj;
      this.not = not;
  };                                                                           
  var unit = {};
  var top = function (dict) {
      return dict.top;
  }; 
  var semigroupArray = new Semigroup($foreign.concatArray);
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };
  var not = function (dict) {
      return dict.not;
  };
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (__dict_Functor_5) {
      return map(__dict_Functor_5);
  };
  var functorArray = new Functor($foreign.arrayMap);
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  };                
  var eqChar = new Eq($foreign.refEq);
  var eq = function (dict) {
      return dict.eq;
  };
  var $eq$eq = function (__dict_Eq_7) {
      return eq(__dict_Eq_7);
  };
  var disj = function (dict) {
      return dict.disj;
  };
  var $$const = function (a) {
      return function (_3) {
          return a;
      };
  };
  var conj = function (dict) {
      return dict.conj;
  }; 
  var boundedBoolean = new Bounded(false, true);
  var bottom = function (dict) {
      return dict.bottom;
  };
  var booleanAlgebraBoolean = new BooleanAlgebra(function () {
      return boundedBoolean;
  }, $foreign.boolAnd, $foreign.boolOr, $foreign.boolNot);
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  }; 
  var append = function (dict) {
      return dict.append;
  };
  var $plus$plus = function (__dict_Semigroup_27) {
      return append(__dict_Semigroup_27);
  };
  var $less$greater = function (__dict_Semigroup_28) {
      return append(__dict_Semigroup_28);
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_2) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_1) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_2(_1));
                  });
              });
          };
      };
  };
  exports["BooleanAlgebra"] = BooleanAlgebra;
  exports["Bounded"] = Bounded;
  exports["Eq"] = Eq;
  exports["Semigroup"] = Semigroup;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["not"] = not;
  exports["disj"] = disj;
  exports["conj"] = conj;
  exports["bottom"] = bottom;
  exports["top"] = top;
  exports["=="] = $eq$eq;
  exports["eq"] = eq;
  exports["++"] = $plus$plus;
  exports["<>"] = $less$greater;
  exports["append"] = append;
  exports["ap"] = ap;
  exports["return"] = $$return;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["<*>"] = $less$times$greater;
  exports["apply"] = apply;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["const"] = $$const;
  exports["flip"] = flip;
  exports["unit"] = unit;
  exports["functorArray"] = functorArray;
  exports["semigroupArray"] = semigroupArray;
  exports["eqChar"] = eqChar;
  exports["boundedBoolean"] = boundedBoolean;
  exports["booleanAlgebraBoolean"] = booleanAlgebraBoolean;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];     
  var Alt = function (__superclass_Prelude$dotFunctor_0, alt) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.alt = alt;
  };                                         
  var alt = function (dict) {
      return dict.alt;
  };
  var $less$bar$greater = function (__dict_Alt_0) {
      return alt(__dict_Alt_0);
  };
  exports["Alt"] = Alt;
  exports["<|>"] = $less$bar$greater;
  exports["alt"] = alt;;
 
})(PS["Control.Alt"] = PS["Control.Alt"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];     
  var Plus = function (__superclass_Control$dotAlt$dotAlt_0, empty) {
      this["__superclass_Control.Alt.Alt_0"] = __superclass_Control$dotAlt$dotAlt_0;
      this.empty = empty;
  };       
  var empty = function (dict) {
      return dict.empty;
  };
  exports["Plus"] = Plus;
  exports["empty"] = empty;;
 
})(PS["Control.Plus"] = PS["Control.Plus"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Plus = PS["Control.Plus"];     
  var Alternative = function (__superclass_Control$dotPlus$dotPlus_1, __superclass_Prelude$dotApplicative_0) {
      this["__superclass_Control.Plus.Plus_1"] = __superclass_Control$dotPlus$dotPlus_1;
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
  };
  exports["Alternative"] = Alternative;;
 
})(PS["Control.Alternative"] = PS["Control.Alternative"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];     
  var Lazy = function (defer) {
      this.defer = defer;
  };
  var defer = function (dict) {
      return dict.defer;
  };
  exports["Lazy"] = Lazy;
  exports["defer"] = defer;;
 
})(PS["Control.Lazy"] = PS["Control.Lazy"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };

  exports.runPure = function (f) {
    return f();
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;
  exports["runPure"] = $foreign.runPure;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.ST

  exports.newSTRef = function (val) {
    return function () {
      return { value: val };
    };
  };

  exports.readSTRef = function (ref) {
    return function () {
      return ref.value;
    };
  };

  exports.writeSTRef = function (ref) {
    return function (a) {
      return function () {
        /* jshint boss: true */
        return ref.value = a;
      };
    };
  };
 
})(PS["Control.Monad.ST"] = PS["Control.Monad.ST"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Control.Monad.ST"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["writeSTRef"] = $foreign.writeSTRef;
  exports["readSTRef"] = $foreign.readSTRef;
  exports["newSTRef"] = $foreign.newSTRef;;
 
})(PS["Control.Monad.ST"] = PS["Control.Monad.ST"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  //------------------------------------------------------------------------------
  // Array size ------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.length = function (xs) {
    return xs.length;
  };

  //------------------------------------------------------------------------------
  // Extending arrays ------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.cons = function (e) {
    return function (l) {
      return [e].concat(l);
    };
  };

  exports.concat = function (xss) {
    var result = [];
    for (var i = 0, l = xss.length; i < l; i++) {
      var xs = xss[i];
      for (var j = 0, m = xs.length; j < m; j++) {
        result.push(xs[j]);
      }
    }
    return result;
  };
 
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Foldable

  exports.foldrArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = len - 1; i >= 0; i--) {
          acc = f(xs[i])(acc);
        }
        return acc;
      };
    };
  };

  exports.foldlArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = 0; i < len; i++) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      };
    };
  };
 
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];     
  var Monoid = function (__superclass_Prelude$dotSemigroup_0, mempty) {
      this["__superclass_Prelude.Semigroup_0"] = __superclass_Prelude$dotSemigroup_0;
      this.mempty = mempty;
  };       
  var mempty = function (dict) {
      return dict.mempty;
  };
  exports["Monoid"] = Monoid;
  exports["mempty"] = mempty;;
 
})(PS["Data.Monoid"] = PS["Data.Monoid"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var maybe = function (b) {
      return function (f) {
          return function (_0) {
              if (_0 instanceof Nothing) {
                  return b;
              };
              if (_0 instanceof Just) {
                  return f(_0.value0);
              };
              throw new Error("Failed pattern match at Data.Maybe line 26, column 1 - line 27, column 1: " + [ b.constructor.name, f.constructor.name, _0.constructor.name ]);
          };
      };
  };                                                   
  var isJust = maybe(false)(Prelude["const"](true));
  var functorMaybe = new Prelude.Functor(function (fn) {
      return function (_2) {
          if (_2 instanceof Just) {
              return new Just(fn(_2.value0));
          };
          return Nothing.value;
      };
  });
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["isJust"] = isJust;
  exports["maybe"] = maybe;
  exports["functorMaybe"] = functorMaybe;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Disj = function (x) {
      return x;
  };
  var semigroupDisj = function (__dict_BooleanAlgebra_2) {
      return new Prelude.Semigroup(function (_10) {
          return function (_11) {
              return Prelude.disj(__dict_BooleanAlgebra_2)(_10)(_11);
          };
      });
  };
  var runDisj = function (_0) {
      return _0;
  };
  var monoidDisj = function (__dict_BooleanAlgebra_4) {
      return new Data_Monoid.Monoid(function () {
          return semigroupDisj(__dict_BooleanAlgebra_4);
      }, Prelude.bottom(__dict_BooleanAlgebra_4["__superclass_Prelude.Bounded_0"]()));
  };
  exports["Disj"] = Disj;
  exports["runDisj"] = runDisj;
  exports["semigroupDisj"] = semigroupDisj;
  exports["monoidDisj"] = monoidDisj;;
 
})(PS["Data.Monoid.Disj"] = PS["Data.Monoid.Disj"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Foldable"];
  var Prelude = PS["Prelude"];
  var Control_Apply = PS["Control.Apply"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Maybe_Last = PS["Data.Maybe.Last"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Monoid_Additive = PS["Data.Monoid.Additive"];
  var Data_Monoid_Conj = PS["Data.Monoid.Conj"];
  var Data_Monoid_Disj = PS["Data.Monoid.Disj"];
  var Data_Monoid_Dual = PS["Data.Monoid.Dual"];
  var Data_Monoid_Endo = PS["Data.Monoid.Endo"];
  var Data_Monoid_Multiplicative = PS["Data.Monoid.Multiplicative"];     
  var Foldable = function (foldMap, foldl, foldr) {
      this.foldMap = foldMap;
      this.foldl = foldl;
      this.foldr = foldr;
  };
  var foldr = function (dict) {
      return dict.foldr;
  };
  var foldl = function (dict) {
      return dict.foldl;
  }; 
  var foldMapDefaultR = function (__dict_Foldable_26) {
      return function (__dict_Monoid_27) {
          return function (f) {
              return function (xs) {
                  return foldr(__dict_Foldable_26)(function (x) {
                      return function (acc) {
                          return Prelude["<>"](__dict_Monoid_27["__superclass_Prelude.Semigroup_0"]())(f(x))(acc);
                      };
                  })(Data_Monoid.mempty(__dict_Monoid_27))(xs);
              };
          };
      };
  };
  var foldableArray = new Foldable(function (__dict_Monoid_28) {
      return foldMapDefaultR(foldableArray)(__dict_Monoid_28);
  }, $foreign.foldlArray, $foreign.foldrArray);
  var foldMap = function (dict) {
      return dict.foldMap;
  };
  var any = function (__dict_Foldable_38) {
      return function (__dict_BooleanAlgebra_39) {
          return function (p) {
              return function (_112) {
                  return Data_Monoid_Disj.runDisj(foldMap(__dict_Foldable_38)(Data_Monoid_Disj.monoidDisj(__dict_BooleanAlgebra_39))(function (_113) {
                      return Data_Monoid_Disj.Disj(p(_113));
                  })(_112));
              };
          };
      };
  };
  var elem = function (__dict_Foldable_40) {
      return function (__dict_Eq_41) {
          return function (_114) {
              return any(__dict_Foldable_40)(Prelude.booleanAlgebraBoolean)(Prelude["=="](__dict_Eq_41)(_114));
          };
      };
  };
  exports["Foldable"] = Foldable;
  exports["elem"] = elem;
  exports["any"] = any;
  exports["foldMapDefaultR"] = foldMapDefaultR;
  exports["foldMap"] = foldMap;
  exports["foldl"] = foldl;
  exports["foldr"] = foldr;
  exports["foldableArray"] = foldableArray;;
 
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Biapplicative = PS["Control.Biapplicative"];
  var Control_Biapply = PS["Control.Biapply"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Control_Lazy = PS["Control.Lazy"];
  var Data_Bifoldable = PS["Data.Bifoldable"];
  var Data_Bifunctor = PS["Data.Bifunctor"];
  var Data_Bitraversable = PS["Data.Bitraversable"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Tuple = (function () {
      function Tuple(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Tuple.create = function (value0) {
          return function (value1) {
              return new Tuple(value0, value1);
          };
      };
      return Tuple;
  })();
  exports["Tuple"] = Tuple;;
 
})(PS["Data.Tuple"] = PS["Data.Tuple"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Array"];
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];     
  var $colon = $foreign.cons;
  var some = function (__dict_Alternative_4) {
      return function (__dict_Lazy_5) {
          return function (v) {
              return Prelude["<*>"]((__dict_Alternative_4["__superclass_Prelude.Applicative_0"]())["__superclass_Prelude.Apply_0"]())(Prelude["<$>"](((__dict_Alternative_4["__superclass_Control.Plus.Plus_1"]())["__superclass_Control.Alt.Alt_0"]())["__superclass_Prelude.Functor_0"]())($colon)(v))(Control_Lazy.defer(__dict_Lazy_5)(function (_5) {
                  return many(__dict_Alternative_4)(__dict_Lazy_5)(v);
              }));
          };
      };
  };
  var many = function (__dict_Alternative_6) {
      return function (__dict_Lazy_7) {
          return function (v) {
              return Control_Alt["<|>"]((__dict_Alternative_6["__superclass_Control.Plus.Plus_1"]())["__superclass_Control.Alt.Alt_0"]())(some(__dict_Alternative_6)(__dict_Lazy_7)(v))(Prelude.pure(__dict_Alternative_6["__superclass_Prelude.Applicative_0"]())([  ]));
          };
      };
  };
  exports["many"] = many;
  exports["some"] = some;;
 
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Array.ST

  exports.runSTArray = function (f) {
    return f;
  };

  exports.emptySTArray = function () {
    return [];
  };

  exports.pushAllSTArray = function (xs) {
    return function (as) {
      return function () {
        return xs.push.apply(xs, as);
      };
    };
  };
 
})(PS["Data.Array.ST"] = PS["Data.Array.ST"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Array.ST"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_ST = PS["Control.Monad.ST"];
  var Data_Maybe = PS["Data.Maybe"];
  var pushSTArray = function (arr) {
      return function (a) {
          return $foreign.pushAllSTArray(arr)([ a ]);
      };
  };
  exports["pushSTArray"] = pushSTArray;
  exports["emptySTArray"] = $foreign.emptySTArray;
  exports["runSTArray"] = $foreign.runSTArray;;
 
})(PS["Data.Array.ST"] = PS["Data.Array.ST"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Char

  exports.toString = function (c) {
    return c;
  };
 
})(PS["Data.Char"] = PS["Data.Char"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Char"];
  var Prelude = PS["Prelude"];
  exports["toString"] = $foreign.toString;;
 
})(PS["Data.Char"] = PS["Data.Char"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Extend = PS["Control.Extend"];
  var Data_Bifoldable = PS["Data.Bifoldable"];
  var Data_Bifunctor = PS["Data.Bifunctor"];
  var Data_Bitraversable = PS["Data.Bitraversable"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Left = (function () {
      function Left(value0) {
          this.value0 = value0;
      };
      Left.create = function (value0) {
          return new Left(value0);
      };
      return Left;
  })();
  var Right = (function () {
      function Right(value0) {
          this.value0 = value0;
      };
      Right.create = function (value0) {
          return new Right(value0);
      };
      return Right;
  })();
  var functorEither = new Prelude.Functor(function (f) {
      return function (_2) {
          if (_2 instanceof Left) {
              return new Left(_2.value0);
          };
          if (_2 instanceof Right) {
              return new Right(f(_2.value0));
          };
          throw new Error("Failed pattern match at Data.Either line 52, column 1 - line 56, column 1: " + [ f.constructor.name, _2.constructor.name ]);
      };
  });
  var either = function (f) {
      return function (g) {
          return function (_1) {
              if (_1 instanceof Left) {
                  return f(_1.value0);
              };
              if (_1 instanceof Right) {
                  return g(_1.value0);
              };
              throw new Error("Failed pattern match at Data.Either line 28, column 1 - line 29, column 1: " + [ f.constructor.name, g.constructor.name, _1.constructor.name ]);
          };
      };
  }; 
  var applyEither = new Prelude.Apply(function () {
      return functorEither;
  }, function (_4) {
      return function (r) {
          if (_4 instanceof Left) {
              return new Left(_4.value0);
          };
          if (_4 instanceof Right) {
              return Prelude["<$>"](functorEither)(_4.value0)(r);
          };
          throw new Error("Failed pattern match at Data.Either line 92, column 1 - line 116, column 1: " + [ _4.constructor.name, r.constructor.name ]);
      };
  });
  var bindEither = new Prelude.Bind(function () {
      return applyEither;
  }, either(function (e) {
      return function (_0) {
          return new Left(e);
      };
  })(function (a) {
      return function (f) {
          return f(a);
      };
  }));
  var applicativeEither = new Prelude.Applicative(function () {
      return applyEither;
  }, Right.create);
  exports["Left"] = Left;
  exports["Right"] = Right;
  exports["either"] = either;
  exports["functorEither"] = functorEither;
  exports["applyEither"] = applyEither;
  exports["applicativeEither"] = applicativeEither;
  exports["bindEither"] = bindEither;;
 
})(PS["Data.Either"] = PS["Data.Either"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Identity = function (x) {
      return x;
  };
  var runIdentity = function (_0) {
      return _0;
  };
  var functorIdentity = new Prelude.Functor(function (f) {
      return function (_23) {
          return f(_23);
      };
  });
  var applyIdentity = new Prelude.Apply(function () {
      return functorIdentity;
  }, function (_24) {
      return function (_25) {
          return _24(_25);
      };
  });
  var bindIdentity = new Prelude.Bind(function () {
      return applyIdentity;
  }, function (_26) {
      return function (f) {
          return f(_26);
      };
  });
  var applicativeIdentity = new Prelude.Applicative(function () {
      return applyIdentity;
  }, Identity);
  var monadIdentity = new Prelude.Monad(function () {
      return applicativeIdentity;
  }, function () {
      return bindIdentity;
  });
  exports["Identity"] = Identity;
  exports["runIdentity"] = runIdentity;
  exports["functorIdentity"] = functorIdentity;
  exports["applyIdentity"] = applyIdentity;
  exports["applicativeIdentity"] = applicativeIdentity;
  exports["bindIdentity"] = bindIdentity;
  exports["monadIdentity"] = monadIdentity;;
 
})(PS["Data.Identity"] = PS["Data.Identity"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Array_ST = PS["Data.Array.ST"];
  var Data_Traversable = PS["Data.Traversable"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_ST = PS["Control.Monad.ST"];     
  var Unfoldable = function (unfoldr) {
      this.unfoldr = unfoldr;
  };
  var unfoldr = function (dict) {
      return dict.unfoldr;
  };
  var unfoldableArray = new Unfoldable(function (f) {
      return function (b) {
          return Control_Monad_Eff.runPure(Data_Array_ST.runSTArray(function __do() {
              var _2 = Data_Array_ST.emptySTArray();
              var _1 = Control_Monad_ST.newSTRef(b)();
              (function () {
                  while (!(function __do() {
                      var _0 = Control_Monad_ST.readSTRef(_1)();
                      return (function () {
                          var _6 = f(_0);
                          if (_6 instanceof Data_Maybe.Nothing) {
                              return Prelude["return"](Control_Monad_Eff.applicativeEff)(true);
                          };
                          if (_6 instanceof Data_Maybe.Just) {
                              return function __do() {
                                  Data_Array_ST.pushSTArray(_2)(_6.value0.value0)();
                                  Control_Monad_ST.writeSTRef(_1)(_6.value0.value1)();
                                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(false)();
                              };
                          };
                          throw new Error("Failed pattern match at Data.Unfoldable line 29, column 1 - line 49, column 1: " + [ _6.constructor.name ]);
                      })()();
                  })()) {

                  };
                  return {};
              })();
              return Prelude["return"](Control_Monad_Eff.applicativeEff)(_2)();
          }));
      };
  });
  exports["Unfoldable"] = Unfoldable;
  exports["unfoldr"] = unfoldr;
  exports["unfoldableArray"] = unfoldableArray;;
 
})(PS["Data.Unfoldable"] = PS["Data.Unfoldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];     
  var Nil = (function () {
      function Nil() {

      };
      Nil.value = new Nil();
      return Nil;
  })();
  var Cons = (function () {
      function Cons(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Cons.create = function (value0) {
          return function (value1) {
              return new Cons(value0, value1);
          };
      };
      return Cons;
  })();
  var $colon = Cons.create;
  var uncons = function (_17) {
      if (_17 instanceof Nil) {
          return Data_Maybe.Nothing.value;
      };
      if (_17 instanceof Cons) {
          return new Data_Maybe.Just({
              head: _17.value0, 
              tail: _17.value1
          });
      };
      throw new Error("Failed pattern match at Data.List line 267, column 1 - line 268, column 1: " + [ _17.constructor.name ]);
  };
  var tail = function (_15) {
      if (_15 instanceof Nil) {
          return Data_Maybe.Nothing.value;
      };
      if (_15 instanceof Cons) {
          return new Data_Maybe.Just(_15.value1);
      };
      throw new Error("Failed pattern match at Data.List line 248, column 1 - line 249, column 1: " + [ _15.constructor.name ]);
  };                     
  var head = function (_13) {
      if (_13 instanceof Nil) {
          return Data_Maybe.Nothing.value;
      };
      if (_13 instanceof Cons) {
          return new Data_Maybe.Just(_13.value0);
      };
      throw new Error("Failed pattern match at Data.List line 233, column 1 - line 234, column 1: " + [ _13.constructor.name ]);
  }; 
  var fromList = function (__dict_Unfoldable_15) {
      return Data_Unfoldable.unfoldr(__dict_Unfoldable_15)(function (xs) {
          return Prelude["<$>"](Data_Maybe.functorMaybe)(function (rec) {
              return new Data_Tuple.Tuple(rec.head, rec.tail);
          })(uncons(xs));
      });
  };
  exports["Nil"] = Nil;
  exports["Cons"] = Cons;
  exports["uncons"] = uncons;
  exports["tail"] = tail;
  exports["head"] = head;
  exports[":"] = $colon;
  exports["fromList"] = fromList;;
 
})(PS["Data.List"] = PS["Data.List"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.String

  exports._charAt = function (just) {
    return function (nothing) {
      return function (i) {
        return function (s) {
          return i >= 0 && i < s.length ? just(s.charAt(i)) : nothing;
        };
      };
    };
  };

  exports.fromCharArray = function (a) {
    return a.join("");
  };

  exports._indexOf = function (just) {
    return function (nothing) {
      return function (x) {
        return function (s) {
          var i = s.indexOf(x);
          return i === -1 ? nothing : just(i);
        };
      };
    };
  };

  exports.length = function (s) {
    return s.length;
  };

  exports.replace = function (s1) {
    return function (s2) {
      return function (s3) {
        return s3.replace(s1, s2);
      };
    };
  };

  exports.drop = function (n) {
    return function (s) {
      return s.substr(n);
    };
  };

  exports.split = function (sep) {
    return function (s) {
      return s.split(sep);
    };
  };

  exports.joinWith = function (s) {
    return function (xs) {
      return xs.join(s);
    };
  };
 
})(PS["Data.String"] = PS["Data.String"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.String"];
  var Prelude = PS["Prelude"];
  var Data_Char = PS["Data.Char"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_String_Unsafe = PS["Data.String.Unsafe"];                                          
  var indexOf = $foreign._indexOf(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var fromChar = Data_Char.toString;
  var singleton = fromChar;
  var contains = function (x) {
      return function (s) {
          return Data_Maybe.isJust(indexOf(x)(s));
      };
  };                                                                                      
  var charAt = $foreign._charAt(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  exports["singleton"] = singleton;
  exports["indexOf"] = indexOf;
  exports["contains"] = contains;
  exports["fromChar"] = fromChar;
  exports["charAt"] = charAt;
  exports["joinWith"] = $foreign.joinWith;
  exports["split"] = $foreign.split;
  exports["drop"] = $foreign.drop;
  exports["replace"] = $foreign.replace;
  exports["length"] = $foreign.length;
  exports["fromCharArray"] = $foreign.fromCharArray;;
 
})(PS["Data.String"] = PS["Data.String"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports["regex'"] = function (s1) {
    return function (s2) {
      return new RegExp(s1, s2);
    };
  };

  exports.replace = function (r) {
    return function (s1) {
      return function (s2) {
        return s2.replace(r, s1);
      };
    };
  };
 
})(PS["Data.String.Regex"] = PS["Data.String.Regex"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.String.Regex"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_String = PS["Data.String"];                                            
  var renderFlags = function (f) {
      return (function () {
          if (f.global) {
              return "g";
          };
          if (!f.global) {
              return "";
          };
          throw new Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: " + [ f.global.constructor.name ]);
      })() + ((function () {
          if (f.ignoreCase) {
              return "i";
          };
          if (!f.ignoreCase) {
              return "";
          };
          throw new Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: " + [ f.ignoreCase.constructor.name ]);
      })() + ((function () {
          if (f.multiline) {
              return "m";
          };
          if (!f.multiline) {
              return "";
          };
          throw new Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: " + [ f.multiline.constructor.name ]);
      })() + ((function () {
          if (f.sticky) {
              return "y";
          };
          if (!f.sticky) {
              return "";
          };
          throw new Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: " + [ f.sticky.constructor.name ]);
      })() + (function () {
          if (f.unicode) {
              return "u";
          };
          if (!f.unicode) {
              return "";
          };
          throw new Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: " + [ f.unicode.constructor.name ]);
      })())));
  };
  var regex = function (s) {
      return function (f) {
          return $foreign["regex'"](s)(renderFlags(f));
      };
  };
  var parseFlags = function (s) {
      return {
          global: Data_String.contains("g")(s), 
          ignoreCase: Data_String.contains("i")(s), 
          multiline: Data_String.contains("m")(s), 
          sticky: Data_String.contains("y")(s), 
          unicode: Data_String.contains("u")(s)
      };
  };
  exports["parseFlags"] = parseFlags;
  exports["renderFlags"] = renderFlags;
  exports["regex"] = regex;
  exports["replace"] = $foreign.replace;;
 
})(PS["Data.String.Regex"] = PS["Data.String.Regex"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_String = PS["Data.String"];
  var Data_Foldable = PS["Data.Foldable"];     
  var Position = (function () {
      function Position(value0) {
          this.value0 = value0;
      };
      Position.create = function (value0) {
          return new Position(value0);
      };
      return Position;
  })();
  var updatePosString = function (pos) {
      return function (str) {
          var updatePosChar = function (_3) {
              return function (c) {
                  if (c === "\n") {
                      return new Position({
                          line: _3.value0.line + 1 | 0, 
                          column: 1
                      });
                  };
                  if (c === "\r") {
                      return new Position({
                          line: _3.value0.line + 1 | 0, 
                          column: 1
                      });
                  };
                  if (c === "\t") {
                      return new Position({
                          line: _3.value0.line, 
                          column: (_3.value0.column + 8 | 0) - (_3.value0.column - 1) % 8
                      });
                  };
                  return new Position({
                      line: _3.value0.line, 
                      column: _3.value0.column + 1 | 0
                  });
              };
          };
          return Data_Foldable.foldl(Data_Foldable.foldableArray)(updatePosChar)(pos)(Data_String.split("")(str));
      };
  }; 
  var initialPos = new Position({
      line: 1, 
      column: 1
  });
  exports["Position"] = Position;
  exports["updatePosString"] = updatePosString;
  exports["initialPos"] = initialPos;;
 
})(PS["Text.Parsing.Parser.Pos"] = PS["Text.Parsing.Parser.Pos"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_Identity = PS["Data.Identity"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Tuple = PS["Data.Tuple"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad = PS["Control.Monad"];
  var Control_Monad_Trans = PS["Control.Monad.Trans"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Control_Monad_State_Trans = PS["Control.Monad.State.Trans"];
  var Control_Monad_Error_Class = PS["Control.Monad.Error.Class"];
  var Control_Monad_Except_Trans = PS["Control.Monad.Except.Trans"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Text_Parsing_Parser_Pos = PS["Text.Parsing.Parser.Pos"];     
  var ParseError = (function () {
      function ParseError(value0) {
          this.value0 = value0;
      };
      ParseError.create = function (value0) {
          return new ParseError(value0);
      };
      return ParseError;
  })();
  var PState = (function () {
      function PState(value0) {
          this.value0 = value0;
      };
      PState.create = function (value0) {
          return new PState(value0);
      };
      return PState;
  })();
  var ParserT = function (x) {
      return x;
  };
  var unParserT = function (_6) {
      return _6;
  }; 
  var runParserT = function (__dict_Monad_0) {
      return function (s) {
          return function (p) {
              return Prelude.bind(__dict_Monad_0["__superclass_Prelude.Bind_1"]())(unParserT(p)(s))(function (_0) {
                  return Prelude["return"](__dict_Monad_0["__superclass_Prelude.Applicative_0"]())(_0.result);
              });
          };
      };
  };
  var runParser = function (s) {
      return function (_40) {
          return Data_Identity.runIdentity(runParserT(Data_Identity.monadIdentity)(new PState({
              input: s, 
              position: Text_Parsing_Parser_Pos.initialPos
          }))(_40));
      };
  };
  var parseFailed = function (s) {
      return function (pos) {
          return function (message) {
              return {
                  input: s, 
                  consumed: false, 
                  result: new Data_Either.Left(new ParseError({
                      message: message, 
                      position: pos
                  })), 
                  position: pos
              };
          };
      };
  }; 
  var lazyParserT = new Control_Lazy.Lazy(function (f) {
      return ParserT(function (s) {
          return unParserT(f(Prelude.unit))(s);
      });
  });
  var functorParserT = function (__dict_Functor_5) {
      return new Prelude.Functor(function (f) {
          return function (p) {
              var f$prime = function (o) {
                  return {
                      input: o.input, 
                      result: Prelude["<$>"](Data_Either.functorEither)(f)(o.result), 
                      consumed: o.consumed, 
                      position: o.position
                  };
              };
              return ParserT(function (s) {
                  return Prelude["<$>"](__dict_Functor_5)(f$prime)(unParserT(p)(s));
              });
          };
      });
  };
  var fail = function (__dict_Monad_6) {
      return function (message) {
          return ParserT(function (_5) {
              return Prelude["return"](__dict_Monad_6["__superclass_Prelude.Applicative_0"]())(parseFailed(_5.value0.input)(_5.value0.position)(message));
          });
      };
  };
  var monadParserT = function (__dict_Monad_4) {
      return new Prelude.Monad(function () {
          return applicativeParserT(__dict_Monad_4);
      }, function () {
          return bindParserT(__dict_Monad_4);
      });
  };
  var bindParserT = function (__dict_Monad_9) {
      return new Prelude.Bind(function () {
          return applyParserT(__dict_Monad_9);
      }, function (p) {
          return function (f) {
              var updateConsumedFlag = function (c) {
                  return function (o) {
                      return {
                          input: o.input, 
                          consumed: c || o.consumed, 
                          result: o.result, 
                          position: o.position
                      };
                  };
              };
              return ParserT(function (s) {
                  return Prelude[">>="](__dict_Monad_9["__superclass_Prelude.Bind_1"]())(unParserT(p)(s))(function (o) {
                      if (o.result instanceof Data_Either.Left) {
                          return Prelude["return"](__dict_Monad_9["__superclass_Prelude.Applicative_0"]())({
                              input: o.input, 
                              result: new Data_Either.Left(o.result.value0), 
                              consumed: o.consumed, 
                              position: o.position
                          });
                      };
                      if (o.result instanceof Data_Either.Right) {
                          return Prelude["<$>"](((__dict_Monad_9["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(updateConsumedFlag(o.consumed))(unParserT(f(o.result.value0))(new PState({
                              input: o.input, 
                              position: o.position
                          })));
                      };
                      throw new Error("Failed pattern match: " + [ o.result.constructor.name ]);
                  });
              });
          };
      });
  };
  var applyParserT = function (__dict_Monad_10) {
      return new Prelude.Apply(function () {
          return functorParserT(((__dict_Monad_10["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]());
      }, Prelude.ap(monadParserT(__dict_Monad_10)));
  };
  var applicativeParserT = function (__dict_Monad_11) {
      return new Prelude.Applicative(function () {
          return applyParserT(__dict_Monad_11);
      }, function (a) {
          return ParserT(function (_1) {
              return Prelude.pure(__dict_Monad_11["__superclass_Prelude.Applicative_0"]())({
                  input: _1.value0.input, 
                  result: new Data_Either.Right(a), 
                  consumed: false, 
                  position: _1.value0.position
              });
          });
      });
  };
  var altParserT = function (__dict_Monad_13) {
      return new Control_Alt.Alt(function () {
          return functorParserT(((__dict_Monad_13["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]());
      }, function (p1) {
          return function (p2) {
              return ParserT(function (s) {
                  return Prelude[">>="](__dict_Monad_13["__superclass_Prelude.Bind_1"]())(unParserT(p1)(s))(function (o) {
                      if (o.result instanceof Data_Either.Left && !o.consumed) {
                          return unParserT(p2)(s);
                      };
                      return Prelude["return"](__dict_Monad_13["__superclass_Prelude.Applicative_0"]())(o);
                  });
              });
          };
      });
  };
  var plusParserT = function (__dict_Monad_7) {
      return new Control_Plus.Plus(function () {
          return altParserT(__dict_Monad_7);
      }, fail(__dict_Monad_7)("No alternative"));
  };
  var alternativeParserT = function (__dict_Monad_12) {
      return new Control_Alternative.Alternative(function () {
          return plusParserT(__dict_Monad_12);
      }, function () {
          return applicativeParserT(__dict_Monad_12);
      });
  };
  exports["ParserT"] = ParserT;
  exports["PState"] = PState;
  exports["ParseError"] = ParseError;
  exports["parseFailed"] = parseFailed;
  exports["fail"] = fail;
  exports["runParser"] = runParser;
  exports["runParserT"] = runParserT;
  exports["unParserT"] = unParserT;
  exports["functorParserT"] = functorParserT;
  exports["applyParserT"] = applyParserT;
  exports["applicativeParserT"] = applicativeParserT;
  exports["altParserT"] = altParserT;
  exports["plusParserT"] = plusParserT;
  exports["alternativeParserT"] = alternativeParserT;
  exports["bindParserT"] = bindParserT;
  exports["monadParserT"] = monadParserT;
  exports["lazyParserT"] = lazyParserT;;
 
})(PS["Text.Parsing.Parser"] = PS["Text.Parsing.Parser"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_String = PS["Data.String"];
  var Data_Array = PS["Data.Array"];
  var Data_String_Regex = PS["Data.String.Regex"];     
  var VarE = (function () {
      function VarE(value0) {
          this.value0 = value0;
      };
      VarE.create = function (value0) {
          return new VarE(value0);
      };
      return VarE;
  })();
  var AppE = (function () {
      function AppE(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      AppE.create = function (value0) {
          return function (value1) {
              return new AppE(value0, value1);
          };
      };
      return AppE;
  })();
  var StringLitE = (function () {
      function StringLitE(value0) {
          this.value0 = value0;
      };
      StringLitE.create = function (value0) {
          return new StringLitE(value0);
      };
      return StringLitE;
  })();
  var ArrayLitE = (function () {
      function ArrayLitE(value0) {
          this.value0 = value0;
      };
      ArrayLitE.create = function (value0) {
          return new ArrayLitE(value0);
      };
      return ArrayLitE;
  })();
  var RawE = (function () {
      function RawE(value0) {
          this.value0 = value0;
      };
      RawE.create = function (value0) {
          return new RawE(value0);
      };
      return RawE;
  })();
  var SigE = (function () {
      function SigE(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      SigE.create = function (value0) {
          return function (value1) {
              return new SigE(value0, value1);
          };
      };
      return SigE;
  })();
  var escapeString = function (str) {
      return Data_String_Regex.replace(Data_String_Regex.regex("\x07")(Data_String_Regex.parseFlags("gm")))("\\a")(Data_String_Regex.replace(Data_String_Regex.regex("\b")(Data_String_Regex.parseFlags("gm")))("\\b")(Data_String_Regex.replace(Data_String_Regex.regex("\f")(Data_String_Regex.parseFlags("gm")))("\\f")(Data_String_Regex.replace(Data_String_Regex.regex("\n")(Data_String_Regex.parseFlags("gm")))("\\n")(Data_String_Regex.replace(Data_String_Regex.regex("\t")(Data_String_Regex.parseFlags("gm")))("\\t")(Data_String_Regex.replace(Data_String_Regex.regex("\r")(Data_String_Regex.parseFlags("gm")))("\\r")(Data_String_Regex.replace(Data_String_Regex.regex("\v")(Data_String_Regex.parseFlags("gm")))("\\v")(Data_String_Regex.replace(Data_String_Regex.regex("\"")(Data_String_Regex.parseFlags("gm")))("\\\"")(Data_String_Regex.replace(Data_String_Regex.regex("'")(Data_String_Regex.parseFlags("gm")))("\\'")(Data_String_Regex.replace(Data_String_Regex.regex("\\\\")(Data_String_Regex.parseFlags("gm")))("\\\\")(str))))))))));
  };
  var toCode = function (_0) {
      if (_0 instanceof VarE) {
          return _0.value0;
      };
      if (_0 instanceof AppE) {
          return Data_String.joinWith(" ")([ "(", toCode(_0.value0), toCode(_0.value1), ")" ]);
      };
      if (_0 instanceof StringLitE) {
          return Data_String.joinWith("")([ "\"", escapeString(_0.value0), "\"" ]);
      };
      if (_0 instanceof ArrayLitE) {
          return "[" + (Data_String.joinWith(", ")(Prelude.map(Prelude.functorArray)(toCode)(_0.value0)) + "]");
      };
      if (_0 instanceof RawE) {
          return Data_String.joinWith(" ")([ "(", _0.value0, "\n  )" ]);
      };
      if (_0 instanceof SigE) {
          return Data_String.joinWith(" ")([ "(", toCode(_0.value0), "::", _0.value1, ")" ]);
      };
      throw new Error("Failed pattern match: " + [ _0.constructor.name ]);
  };
  exports["VarE"] = VarE;
  exports["AppE"] = AppE;
  exports["StringLitE"] = StringLitE;
  exports["ArrayLitE"] = ArrayLitE;
  exports["RawE"] = RawE;
  exports["SigE"] = SigE;
  exports["toCode"] = toCode;;
 
})(PS["Text.Hatter.PureScript"] = PS["Text.Hatter.PureScript"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Either = PS["Data.Either"];
  var Data_List = PS["Data.List"];
  var Data_Foldable = PS["Data.Foldable"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad = PS["Control.Monad"];
  var Control_Monad_Error_Class = PS["Control.Monad.Error.Class"];
  var Control_Monad_State_Trans = PS["Control.Monad.State.Trans"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Text_Parsing_Parser = PS["Text.Parsing.Parser"];
  var $$try = function (__dict_Functor_1) {
      return function (p) {
          var try$prime = function (s) {
              return function (pos) {
                  return function (_23) {
                      if (_23.result instanceof Data_Either.Left) {
                          return {
                              input: s, 
                              result: _23.result, 
                              consumed: false, 
                              position: pos
                          };
                      };
                      return _23;
                  };
              };
          };
          return Text_Parsing_Parser.ParserT(function (_20) {
              return Prelude["<$>"](__dict_Functor_1)(try$prime(_20.value0.input)(_20.value0.position))(Text_Parsing_Parser.unParserT(p)(new Text_Parsing_Parser.PState({
                  input: _20.value0.input, 
                  position: _20.value0.position
              })));
          });
      };
  };
  var skipMany1 = function (__dict_Monad_2) {
      return function (p) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_2))(p)(function (_14) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_2))(skipMany(__dict_Monad_2)(p))(function (_13) {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_2))(Prelude.unit);
              });
          });
      };
  };
  var skipMany = function (__dict_Monad_3) {
      return function (p) {
          return Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_3))(skipMany1(__dict_Monad_3)(p))(Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_3))(Prelude.unit));
      };
  };
  var manyTill = function (__dict_Monad_12) {
      return function (p) {
          return function (end) {
              var scan = Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_12))(Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_12))(end)(function () {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_12))(Data_List.Nil.value);
              }))(Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_12))(p)(function (_17) {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_12))(scan)(function (_16) {
                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_12))(Data_List[":"](_17)(_16));
                  });
              }));
              return scan;
          };
      };
  };
  var many1Till = function (__dict_Monad_13) {
      return function (p) {
          return function (end) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_13))(p)(function (_19) {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_13))(manyTill(__dict_Monad_13)(p)(end))(function (_18) {
                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_13))(Data_List[":"](_19)(_18));
                  });
              });
          };
      };
  };
  var lookAhead = function (__dict_Monad_14) {
      return function (_22) {
          return function (_21) {
              return Prelude.bind(__dict_Monad_14["__superclass_Prelude.Bind_1"]())(_22(new Text_Parsing_Parser.PState({
                  input: _21.value0.input, 
                  position: _21.value0.position
              })))(function (_15) {
                  return Prelude["return"](__dict_Monad_14["__superclass_Prelude.Applicative_0"]())((function () {
                      var _46 = {};
                      for (var _47 in _15) {
                          if (_15.hasOwnProperty(_47)) {
                              _46[_47] = _15[_47];
                          };
                      };
                      _46.input = _21.value0.input;
                      _46.consumed = false;
                      _46.position = _21.value0.position;
                      return _46;
                  })());
              });
          };
      };
  };
  var choice = function (__dict_Foldable_17) {
      return function (__dict_Monad_18) {
          return Data_Foldable.foldl(__dict_Foldable_17)(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_18)))(Control_Plus.empty(Text_Parsing_Parser.plusParserT(__dict_Monad_18)));
      };
  };
  var between = function (__dict_Monad_25) {
      return function (open) {
          return function (close) {
              return function (p) {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_25))(open)(function () {
                      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_25))(p)(function (_0) {
                          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_25))(close)(function () {
                              return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_25))(_0);
                          });
                      });
                  });
              };
          };
      };
  };
  exports["many1Till"] = many1Till;
  exports["manyTill"] = manyTill;
  exports["lookAhead"] = lookAhead;
  exports["skipMany1"] = skipMany1;
  exports["skipMany"] = skipMany;
  exports["choice"] = choice;
  exports["try"] = $$try;
  exports["between"] = between;;
 
})(PS["Text.Parsing.Parser.Combinators"] = PS["Text.Parsing.Parser.Combinators"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_String = PS["Data.String"];
  var Data_Either = PS["Data.Either"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Char = PS["Data.Char"];
  var Data_Array = PS["Data.Array"];
  var Data_List = PS["Data.List"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Monad_Error_Class = PS["Control.Monad.Error.Class"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Text_Parsing_Parser = PS["Text.Parsing.Parser"];
  var Text_Parsing_Parser_Combinators = PS["Text.Parsing.Parser.Combinators"];
  var Text_Parsing_Parser_Pos = PS["Text.Parsing.Parser.Pos"];     
  var string = function (__dict_Monad_0) {
      return function (str) {
          return Text_Parsing_Parser.ParserT(function (_4) {
              return Prelude["return"](__dict_Monad_0["__superclass_Prelude.Applicative_0"]())((function () {
                  var _7 = Data_String.indexOf(str)(_4.value0.input);
                  if (_7 instanceof Data_Maybe.Just && _7.value0 === 0) {
                      return {
                          consumed: true, 
                          input: Data_String.drop(Data_String.length(str))(_4.value0.input), 
                          result: new Data_Either.Right(str), 
                          position: Text_Parsing_Parser_Pos.updatePosString(_4.value0.position)(str)
                      };
                  };
                  return Text_Parsing_Parser.parseFailed(_4.value0.input)(_4.value0.position)("Expected " + str);
              })());
          });
      };
  };
  var eof = function (__dict_Monad_1) {
      return Text_Parsing_Parser.ParserT(function (_3) {
          return Prelude["return"](__dict_Monad_1["__superclass_Prelude.Applicative_0"]())((function () {
              if (_3.value0.input === "") {
                  return {
                      consumed: false, 
                      input: _3.value0.input, 
                      result: new Data_Either.Right(Prelude.unit), 
                      position: _3.value0.position
                  };
              };
              return Text_Parsing_Parser.parseFailed(_3.value0.input)(_3.value0.position)("Expected EOF");
          })());
      });
  };
  var anyChar = function (__dict_Monad_2) {
      return Text_Parsing_Parser.ParserT(function (_5) {
          return Prelude["return"](__dict_Monad_2["__superclass_Prelude.Applicative_0"]())((function () {
              var _18 = Data_String.charAt(0)(_5.value0.input);
              if (_18 instanceof Data_Maybe.Nothing) {
                  return Text_Parsing_Parser.parseFailed(_5.value0.input)(_5.value0.position)("Unexpected EOF");
              };
              if (_18 instanceof Data_Maybe.Just) {
                  return {
                      consumed: true, 
                      input: Data_String.drop(1)(_5.value0.input), 
                      result: new Data_Either.Right(_18.value0), 
                      position: Text_Parsing_Parser_Pos.updatePosString(_5.value0.position)(Data_Char.toString(_18.value0))
                  };
              };
              throw new Error("Failed pattern match at Text.Parsing.Parser.String line 40, column 1 - line 41, column 1: " + [ _18.constructor.name ]);
          })());
      });
  };
  var satisfy = function (__dict_Monad_3) {
      return function (f) {
          return Text_Parsing_Parser_Combinators["try"](((__dict_Monad_3["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_3))(anyChar(__dict_Monad_3))(function (_1) {
              var _24 = f(_1);
              if (_24) {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_3))(_1);
              };
              if (!_24) {
                  return Text_Parsing_Parser.fail(__dict_Monad_3)("Character '" + (Data_String.fromChar(_1) + "' did not satisfy predicate"));
              };
              throw new Error("Failed pattern match at Text.Parsing.Parser.String line 47, column 1 - line 48, column 1: " + [ _24.constructor.name ]);
          }));
      };
  };
  var oneOf = function (__dict_Monad_6) {
      return function (ss) {
          return satisfy(__dict_Monad_6)(Prelude.flip(Data_Foldable.elem(Data_Foldable.foldableArray)(Prelude.eqChar))(ss));
      };
  };
  var whiteSpace = function (__dict_Monad_7) {
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_7))(Data_Array.many(Text_Parsing_Parser.alternativeParserT(__dict_Monad_7))(Text_Parsing_Parser.lazyParserT)(satisfy(__dict_Monad_7)(function (c) {
          return Prelude["=="](Prelude.eqChar)(c)("\n") || (Prelude["=="](Prelude.eqChar)(c)("\r") || (Prelude["=="](Prelude.eqChar)(c)(" ") || Prelude["=="](Prelude.eqChar)(c)("\t")));
      })))(function (_2) {
          return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_7))(Data_String.fromCharArray(_2));
      });
  };
  var skipSpaces = function (__dict_Monad_8) {
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_8))(whiteSpace(__dict_Monad_8))(function () {
          return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_8))(Prelude.unit);
      });
  };
  exports["oneOf"] = oneOf;
  exports["skipSpaces"] = skipSpaces;
  exports["whiteSpace"] = whiteSpace;
  exports["satisfy"] = satisfy;
  exports["anyChar"] = anyChar;
  exports["string"] = string;
  exports["eof"] = eof;;
 
})(PS["Text.Parsing.Parser.String"] = PS["Text.Parsing.Parser.String"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Data_String = PS["Data.String"];
  var Data_Either = PS["Data.Either"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_List = PS["Data.List"];
  var Data_Array = PS["Data.Array"];
  var Control_Alt = PS["Control.Alt"];
  var Text_Parsing_Parser = PS["Text.Parsing.Parser"];
  var Text_Parsing_Parser_Combinators = PS["Text.Parsing.Parser.Combinators"];
  var Text_Parsing_Parser_String = PS["Text.Parsing.Parser.String"];
  var Prelude = PS["Prelude"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Identity = PS["Data.Identity"];
  var StringLiteral = (function () {
      function StringLiteral(value0) {
          this.value0 = value0;
      };
      StringLiteral.create = function (value0) {
          return new StringLiteral(value0);
      };
      return StringLiteral;
  })();
  var StringExp = (function () {
      function StringExp(value0) {
          this.value0 = value0;
      };
      StringExp.create = function (value0) {
          return new StringExp(value0);
      };
      return StringExp;
  })();
  var Attr = (function () {
      function Attr(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Attr.create = function (value0) {
          return function (value1) {
              return new Attr(value0, value1);
          };
      };
      return Attr;
  })();
  var Toggle = (function () {
      function Toggle(value0) {
          this.value0 = value0;
      };
      Toggle.create = function (value0) {
          return new Toggle(value0);
      };
      return Toggle;
  })();
  var AttributesExp = (function () {
      function AttributesExp(value0) {
          this.value0 = value0;
      };
      AttributesExp.create = function (value0) {
          return new AttributesExp(value0);
      };
      return AttributesExp;
  })();
  var ElementNode = (function () {
      function ElementNode(value0, value1, value2) {
          this.value0 = value0;
          this.value1 = value1;
          this.value2 = value2;
      };
      ElementNode.create = function (value0) {
          return function (value1) {
              return function (value2) {
                  return new ElementNode(value0, value1, value2);
              };
          };
      };
      return ElementNode;
  })();
  var TextNode = (function () {
      function TextNode(value0) {
          this.value0 = value0;
      };
      TextNode.create = function (value0) {
          return new TextNode(value0);
      };
      return TextNode;
  })();
  var RawTextNode = (function () {
      function RawTextNode(value0) {
          this.value0 = value0;
      };
      RawTextNode.create = function (value0) {
          return new RawTextNode(value0);
      };
      return RawTextNode;
  })();
  var NodeExp = (function () {
      function NodeExp(value0) {
          this.value0 = value0;
      };
      NodeExp.create = function (value0) {
          return new NodeExp(value0);
      };
      return NodeExp;
  })();
  var voidElementTags = [ "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "menuitem", "meta", "param", "source", "track", "wbr" ];
  var unify = function (__dict_Functor_0) {
      return function (__dict_Monad_1) {
          return function (parser) {
              return Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_0))(function (_21) {
                  return Prelude.unit;
              })(parser);
          };
      };
  };
  var unescapeHtml = function (html) {
      return Data_String.replace("&amp;")("&")(Data_String.replace("&lt;")("<")(Data_String.replace("&gt;")(">")(html)));
  };
  var stringTill = function (__dict_Functor_2) {
      return function (__dict_Monad_3) {
          return function (end) {
              return Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_2))(function (_101) {
                  return Data_String.fromCharArray(Data_List.fromList(Data_Unfoldable.unfoldableArray)(_101));
              })(Text_Parsing_Parser_Combinators.manyTill(__dict_Monad_3)(Text_Parsing_Parser_String.anyChar(__dict_Monad_3))(end));
          };
      };
  };
  var someWhiteSpaces = function (__dict_Functor_4) {
      return function (__dict_Monad_5) {
          var space = Text_Parsing_Parser_String.oneOf(__dict_Monad_5)([ "\n", "\r", " ", "\t" ]);
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_5))(space)(function (_20) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_5))(Text_Parsing_Parser_String.whiteSpace(__dict_Monad_5))(function (_19) {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_5))(Data_String.singleton(_20) + _19);
              });
          });
      };
  };
  var rawElementTags = [ "script", "style" ];
  var pTextNode = function (__dict_Functor_6) {
      return function (__dict_Monad_7) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_7))(stringTill(__dict_Functor_6)(__dict_Monad_7)(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_7)(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_7))(unify(__dict_Functor_6)(__dict_Monad_7)(Text_Parsing_Parser_String.string(__dict_Monad_7)("<")))(Text_Parsing_Parser_String.eof(__dict_Monad_7)))))(function (_4) {
              return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_7))(TextNode.create(unescapeHtml(_4)));
          });
      };
  };
  var pTagNameOneOf = function (__dict_Monad_8) {
      return function (tags) {
          return function (end) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_8))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_8))(function () {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_8))(Text_Parsing_Parser_Combinators.choice(Data_Foldable.foldableArray)(__dict_Monad_8)(Prelude.map(Prelude.functorArray)(Text_Parsing_Parser_String.string(__dict_Monad_8))(tags)))(function (_14) {
                      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_8))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_8)(end))(function () {
                          return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_8))(_14);
                      });
                  });
              });
          };
      };
  };
  var pTagName = function (__dict_Monad_9) {
      return function (end) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_9))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_9))(function () {
              return stringTill(((__dict_Monad_9["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_9)(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_9)(end));
          });
      };
  };
  var pIndent = function (__dict_Monad_10) {
      return unify(((__dict_Monad_10["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_10)(Text_Parsing_Parser_String.oneOf(__dict_Monad_10)([ " ", "\t" ]));
  };
  var skipEmptyLines = function (__dict_Monad_11) {
      var emptyLine = Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_11))(Data_Array.many(Text_Parsing_Parser.alternativeParserT(__dict_Monad_11))(Text_Parsing_Parser.lazyParserT)(pIndent(__dict_Monad_11)))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_11))(Text_Parsing_Parser_String.oneOf(__dict_Monad_11)([ "\n", "\r" ]))(function () {
              return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_11))(Prelude.unit);
          });
      });
      return Text_Parsing_Parser_Combinators.skipMany(__dict_Monad_11)(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_11["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(emptyLine));
  };
  var pHExp = function (__dict_Monad_12) {
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_12))(Text_Parsing_Parser_String.string(__dict_Monad_12)("<%"))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_12))(stringTill(((__dict_Monad_12["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_12)(Text_Parsing_Parser_String.string(__dict_Monad_12)("%>")))(function (_18) {
              return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_12))(_18);
          });
      });
  };
  var pHString = function (__dict_Functor_13) {
      return function (__dict_Monad_14) {
          return function (end) {
              return Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_14))(Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_13))(StringExp.create)(pHExp(__dict_Monad_14)))(Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_13))(function (_102) {
                  return StringLiteral.create(unescapeHtml(_102));
              })(stringTill(__dict_Functor_13)(__dict_Monad_14)(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_14)(end))));
          };
      };
  };
  var pHStrings = function (__dict_Monad_15) {
      return function (end) {
          return Prelude["<$>"](Text_Parsing_Parser.functorParserT(((__dict_Monad_15["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]()))(Data_List.fromList(Data_Unfoldable.unfoldableArray))(Text_Parsing_Parser_Combinators.manyTill(__dict_Monad_15)(pHString(((__dict_Monad_15["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_15)(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_15)(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_15))(unify(((__dict_Monad_15["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_15)(Text_Parsing_Parser_String.string(__dict_Monad_15)("<%")))(unify(((__dict_Monad_15["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_15)(end)))))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_15)(end)));
      };
  };
  var pRawTextNode = function (__dict_Functor_16) {
      return function (__dict_Monad_17) {
          return function (end) {
              return Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_16))(RawTextNode.create)(pHStrings(__dict_Monad_17)(end));
          };
      };
  };
  var pSingleQuotedHStrings = function (__dict_Monad_18) {
      var sq = Text_Parsing_Parser_String.string(__dict_Monad_18)("'");
      return Text_Parsing_Parser_Combinators.between(__dict_Monad_18)(sq)(sq)(pHStrings(__dict_Monad_18)(sq));
  };
  var pToggle = function (__dict_Monad_19) {
      return function (end) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_19))(pHStrings(__dict_Monad_19)(end))(function (_17) {
              return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_19))(new Toggle(_17));
          });
      };
  };
  var pNodeExp = function (__dict_Functor_20) {
      return function (__dict_Monad_21) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_21))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_21))(function () {
              return Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_20))(NodeExp.create)(pHExp(__dict_Monad_21));
          });
      };
  };
  var pEndTag = function (__dict_Monad_22) {
      return function (tag) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_22))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_22))(function () {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_22))(Text_Parsing_Parser_String.string(__dict_Monad_22)(Data_String.joinWith("")([ "</", tag, ">" ])))(function () {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_22))(Prelude.unit);
              });
          });
      };
  };
  var pDoubleQuotedHStrings = function (__dict_Monad_23) {
      var dq = Text_Parsing_Parser_String.string(__dict_Monad_23)("\"");
      return Text_Parsing_Parser_Combinators.between(__dict_Monad_23)(dq)(dq)(pHStrings(__dict_Monad_23)(dq));
  };
  var pAttributesExp = function (__dict_Functor_24) {
      return function (__dict_Monad_25) {
          return Prelude["<$>"](Text_Parsing_Parser.functorParserT(__dict_Functor_24))(AttributesExp.create)(pHExp(__dict_Monad_25));
      };
  };
  var pAttributeValue = function (__dict_Monad_27) {
      return function (end) {
          return Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_27))(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_27))(pDoubleQuotedHStrings(__dict_Monad_27))(pSingleQuotedHStrings(__dict_Monad_27)))(pHStrings(__dict_Monad_27)(end));
      };
  };
  var pAttr = function (__dict_Monad_29) {
      return function (end) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_29))(pHStrings(__dict_Monad_29)(Text_Parsing_Parser_String.string(__dict_Monad_29)("=")))(function (_16) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_29))(Text_Parsing_Parser_String.string(__dict_Monad_29)("="))(function () {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_29))(pAttributeValue(__dict_Monad_29)(end))(function (_15) {
                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_29))(new Attr(_16, _15));
                  });
              });
          });
      };
  };
  var pAttribute = function (__dict_Monad_30) {
      return function (attrsEnd) {
          var end = Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_30))(unify(((__dict_Monad_30["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_30)(Text_Parsing_Parser_String.string(__dict_Monad_30)(" ")))(unify(((__dict_Monad_30["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_30)(attrsEnd));
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_30))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_30))(function () {
              return Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_30))(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_30))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_30["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pAttributesExp(((__dict_Monad_30["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_30)))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_30["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pAttr(__dict_Monad_30)(end))))(pToggle(__dict_Monad_30)(end));
          });
      };
  };
  var pAttributes = function (__dict_Monad_31) {
      return function (end) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_31))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_31))(function () {
              return Prelude["<$>"](Text_Parsing_Parser.functorParserT(((__dict_Monad_31["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]()))(Data_List.fromList(Data_Unfoldable.unfoldableArray))(Text_Parsing_Parser_Combinators.manyTill(__dict_Monad_31)(pAttribute(__dict_Monad_31)(end))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_31)(end)));
          });
      };
  };
  var pStartTag = function (__dict_Monad_32) {
      return function (pTagName_1) {
          return function (allowSlash) {
              var end = Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_32))(function () {
                  if (allowSlash) {
                      return Text_Parsing_Parser_Combinators.choice(Data_Foldable.foldableArray)(__dict_Monad_32)(Prelude.map(Prelude.functorArray)(Text_Parsing_Parser_String.string(__dict_Monad_32))([ ">", "/>" ]));
                  };
                  if (!allowSlash) {
                      return Text_Parsing_Parser_String.string(__dict_Monad_32)(">");
                  };
                  throw new Error("Failed pattern match at Text.Hatter.Parser line 161, column 5 - line 167, column 1: " + [ allowSlash.constructor.name ]);
              });
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_32))(function () {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(Text_Parsing_Parser_String.string(__dict_Monad_32)("<"))(function () {
                      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(pTagName_1)(function (_13) {
                          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(pAttributes(__dict_Monad_32)(end))(function (_12) {
                              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_32))(function () {
                                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_32))(end)(function () {
                                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_32))(new Data_Tuple.Tuple(_13, _12));
                                  });
                              });
                          });
                      });
                  });
              });
          };
      };
  };
  var pRawElement = function (__dict_Monad_33) {
      var end = Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_33))(someWhiteSpaces(((__dict_Monad_33["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_33))(Text_Parsing_Parser_String.string(__dict_Monad_33)(">"));
      var pStartTagRaw = pStartTag(__dict_Monad_33)(pTagNameOneOf(__dict_Monad_33)(rawElementTags)(end))(false);
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_33))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_33))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_33))(pStartTagRaw)(function (_7) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_33))(Text_Parsing_Parser_Combinators.manyTill(__dict_Monad_33)(pRawTextNode(((__dict_Monad_33["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_33)(pEndTag(__dict_Monad_33)(_7.value0)))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_33)(pEndTag(__dict_Monad_33)(_7.value0))))(function (_6) {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_33))(pEndTag(__dict_Monad_33)(_7.value0))(function () {
                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_33))(ElementNode.create(_7.value0)(_7.value1)(Data_List.fromList(Data_Unfoldable.unfoldableArray)(_6)));
                  });
              });
          });
      });
  };
  var pVoidElement = function (__dict_Monad_34) {
      var end = Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_34))(someWhiteSpaces(((__dict_Monad_34["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_34))(Text_Parsing_Parser_Combinators.choice(Data_Foldable.foldableArray)(__dict_Monad_34)(Prelude.map(Prelude.functorArray)(Text_Parsing_Parser_String.string(__dict_Monad_34))([ ">", "/>" ])));
      var pStartTagVoid = pStartTag(__dict_Monad_34)(pTagNameOneOf(__dict_Monad_34)(voidElementTags)(end))(true);
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_34))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_34))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_34))(pStartTagVoid)(function (_5) {
              return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_34))(new ElementNode(_5.value0, _5.value1, [  ]));
          });
      });
  };
  var line = function (__dict_Monad_35) {
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_35))(stringTill(((__dict_Monad_35["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_35)(Text_Parsing_Parser_String.string(__dict_Monad_35)("\n")))(function (_3) {
          return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_35))(_3 + "\n");
      });
  };
  var escapableRawElementTags = [ "textarea", "title" ];
  var pEscapableRawElement = function (__dict_Monad_36) {
      var end = Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_36))(someWhiteSpaces(((__dict_Monad_36["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_36))(Text_Parsing_Parser_String.string(__dict_Monad_36)(">"));
      var pStartTagEscapableRaw = pStartTag(__dict_Monad_36)(pTagNameOneOf(__dict_Monad_36)(escapableRawElementTags)(end))(false);
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_36))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_36))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_36))(pStartTagEscapableRaw)(function (_9) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_36))(Text_Parsing_Parser_Combinators.manyTill(__dict_Monad_36)(pRawTextNode(((__dict_Monad_36["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_36)(pEndTag(__dict_Monad_36)(_9.value0)))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_36)(pEndTag(__dict_Monad_36)(_9.value0))))(function (_8) {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_36))(pEndTag(__dict_Monad_36)(_9.value0))(function () {
                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_36))(ElementNode.create(_9.value0)(_9.value1)(Data_List.fromList(Data_Unfoldable.unfoldableArray)(_8)));
                  });
              });
          });
      });
  };
  var pNormalElement = function (__dict_Monad_37) {
      var end = Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_37))(someWhiteSpaces(((__dict_Monad_37["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_37))(Text_Parsing_Parser_String.string(__dict_Monad_37)(">"));
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_37))(Text_Parsing_Parser_String.skipSpaces(__dict_Monad_37))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_37))(pStartTag(__dict_Monad_37)(pTagName(__dict_Monad_37)(end))(false))(function (_11) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_37))(Text_Parsing_Parser_Combinators.manyTill(__dict_Monad_37)(pNode(__dict_Monad_37))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_37)(pEndTag(__dict_Monad_37)(_11.value0))))(function (_10) {
                  return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_37))(pEndTag(__dict_Monad_37)(_11.value0))(function () {
                      return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_37))(ElementNode.create(_11.value0)(_11.value1)(Data_List.fromList(Data_Unfoldable.unfoldableArray)(_10)));
                  });
              });
          });
      });
  };
  var pNode = function (__dict_Monad_39) {
      return Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_39))(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_39))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_39["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pNodeExp(((__dict_Monad_39["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_39)))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_39["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pElementNode(__dict_Monad_39))))(pTextNode(((__dict_Monad_39["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(__dict_Monad_39));
  };
  var pElementNode = function (__dict_Monad_38) {
      return Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_38))(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_38))(Control_Alt["<|>"](Text_Parsing_Parser.altParserT(__dict_Monad_38))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_38["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pVoidElement(__dict_Monad_38)))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_38["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pRawElement(__dict_Monad_38))))(Text_Parsing_Parser_Combinators["try"](((__dict_Monad_38["__superclass_Prelude.Bind_1"]())["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(pEscapableRawElement(__dict_Monad_38))))(pNormalElement(__dict_Monad_38));
  };
  var pDeclaration = function (__dict_Monad_40) {
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_40))(Text_Parsing_Parser_Combinators.many1Till(__dict_Monad_40)(line(__dict_Monad_40))(Text_Parsing_Parser_Combinators.lookAhead(__dict_Monad_40)(pIndent(__dict_Monad_40))))(function (_2) {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_40))(pNode(__dict_Monad_40))(function (_1) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_40))(skipEmptyLines(__dict_Monad_40))(function () {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_40))({
                      rawCode: Data_String.joinWith("")(Data_List.fromList(Data_Unfoldable.unfoldableArray)(_2)), 
                      body: _1
                  });
              });
          });
      });
  };
  var pModule = function (__dict_Monad_41) {
      return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_41))(skipEmptyLines(__dict_Monad_41))(function () {
          return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_41))(Data_Array.many(Text_Parsing_Parser.alternativeParserT(__dict_Monad_41))(Text_Parsing_Parser.lazyParserT)(pDeclaration(__dict_Monad_41)))(function (_0) {
              return Prelude.bind(Text_Parsing_Parser.bindParserT(__dict_Monad_41))(Text_Parsing_Parser_String.eof(__dict_Monad_41))(function () {
                  return Prelude["return"](Text_Parsing_Parser.applicativeParserT(__dict_Monad_41))(_0);
              });
          });
      });
  };
  var parse = function (input) {
      return Text_Parsing_Parser.runParser(input)(pModule(Data_Identity.monadIdentity));
  };
  exports["StringLiteral"] = StringLiteral;
  exports["StringExp"] = StringExp;
  exports["Attr"] = Attr;
  exports["Toggle"] = Toggle;
  exports["AttributesExp"] = AttributesExp;
  exports["ElementNode"] = ElementNode;
  exports["TextNode"] = TextNode;
  exports["RawTextNode"] = RawTextNode;
  exports["NodeExp"] = NodeExp;
  exports["parse"] = parse;;
 
})(PS["Text.Hatter.Parser"] = PS["Text.Hatter.Parser"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Bind = PS["Control.Bind"];
  var Text_Hatter_Parser = PS["Text.Hatter.Parser"];
  var Text_Hatter_PureScript = PS["Text.Hatter.PureScript"];
  var Data_String = PS["Data.String"];
  var Data_Either = PS["Data.Either"];
  var Data_Foreign = PS["Data.Foreign"];     
  var translateHString = function (_3) {
      if (_3 instanceof Text_Hatter_Parser.StringLiteral) {
          return new Text_Hatter_PureScript.StringLitE(_3.value0);
      };
      if (_3 instanceof Text_Hatter_Parser.StringExp) {
          return Text_Hatter_PureScript.AppE.create(new Text_Hatter_PureScript.VarE("UC.coerceToString"))(new Text_Hatter_PureScript.RawE(_3.value0));
      };
      throw new Error("Failed pattern match at Text.Hatter.Translator line 69, column 1 - line 70, column 1: " + [ _3.constructor.name ]);
  };
  var translateHStrings = function (xs) {
      return new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("Data.String.joinWith"), new Text_Hatter_PureScript.StringLitE("")), Text_Hatter_PureScript.ArrayLitE.create(Prelude.map(Prelude.functorArray)(translateHString)(xs)));
  };
  var translateAttribute = function (_2) {
      if (_2 instanceof Text_Hatter_Parser.Attr) {
          return new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.prop"), new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.propName"), translateHStrings(_2.value0))), new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.attrName"), translateHStrings(_2.value0))), translateHStrings(_2.value1));
      };
      if (_2 instanceof Text_Hatter_Parser.Toggle) {
          return new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.prop"), new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.propName"), translateHStrings(_2.value0))), new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.attrName"), translateHStrings(_2.value0))), new Text_Hatter_PureScript.VarE("true"));
      };
      if (_2 instanceof Text_Hatter_Parser.AttributesExp) {
          return new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("UC.coerceToProperty"), new Text_Hatter_PureScript.RawE(_2.value0));
      };
      throw new Error("Failed pattern match at Text.Hatter.Translator line 39, column 1 - line 40, column 1: " + [ _2.constructor.name ]);
  };
  var translateNodes = function (_1) {
      if (_1 instanceof Text_Hatter_Parser.NodeExp) {
          return Text_Hatter_PureScript.AppE.create(new Text_Hatter_PureScript.VarE("UC.coerceToElements"))(new Text_Hatter_PureScript.RawE(_1.value0));
      };
      return new Text_Hatter_PureScript.ArrayLitE([ translateNode(_1) ]);
  };
  var translateNode = function (_0) {
      if (_0 instanceof Text_Hatter_Parser.ElementNode) {
          return new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.element"), new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("C.tagName"), new Text_Hatter_PureScript.StringLitE(_0.value0))), Text_Hatter_PureScript.ArrayLitE.create(Prelude.map(Prelude.functorArray)(translateAttribute)(_0.value1))), new Text_Hatter_PureScript.AppE(new Text_Hatter_PureScript.VarE("Contro.Bind.join"), Text_Hatter_PureScript.ArrayLitE.create(Prelude.map(Prelude.functorArray)(translateNodes)(_0.value2))));
      };
      if (_0 instanceof Text_Hatter_Parser.TextNode) {
          return Text_Hatter_PureScript.AppE.create(new Text_Hatter_PureScript.VarE("H.text"))(new Text_Hatter_PureScript.StringLitE(_0.value0));
      };
      if (_0 instanceof Text_Hatter_Parser.RawTextNode) {
          return Text_Hatter_PureScript.AppE.create(new Text_Hatter_PureScript.VarE("H.text"))(translateHStrings(_0.value0));
      };
      if (_0 instanceof Text_Hatter_Parser.NodeExp) {
          return Text_Hatter_PureScript.AppE.create(new Text_Hatter_PureScript.VarE("UC.coerceToElement"))(new Text_Hatter_PureScript.RawE(_0.value0));
      };
      throw new Error("Failed pattern match: " + [ _0.constructor.name ]);
  };
  exports["translateNodes"] = translateNodes;
  exports["translateNode"] = translateNode;;
 
})(PS["Text.Hatter.Translator"] = PS["Text.Hatter.Translator"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_String = PS["Data.String"];
  var Text_Parsing_Parser = PS["Text.Parsing.Parser"];
  var Text_Hatter_PureScript = PS["Text.Hatter.PureScript"];
  var Text_Hatter_Translator = PS["Text.Hatter.Translator"];
  var Text_Hatter_Parser = PS["Text.Hatter.Parser"];     
  var hatter = function (imports) {
      return function (input) {
          var translateDeclaration = function (_1) {
              return _1.rawCode + ("  " + (Text_Hatter_PureScript.toCode(Text_Hatter_Translator.translateNode(_1.body)) + "\n\n"));
          };
          return Prelude.bind(Data_Either.bindEither)(Text_Hatter_Parser.parse(input))(function (_0) {
              return Prelude["return"](Data_Either.applicativeEither)(Data_String.joinWith("")(Prelude["++"](Prelude.semigroupArray)(Prelude.map(Prelude.functorArray)(translateDeclaration)(_0))(Prelude.map(Prelude.functorArray)(function (i) {
                  return "import " + (i + "\n");
              })(imports))));
          });
      };
  };
  exports["hatter"] = hatter;;
 
})(PS["Text.Hatter"] = PS["Text.Hatter"] || {});
module.exports = PS['Text.Hatter'].hatter;
